#!/bin/sh

# Pre-commit hook                                         
# ---------------
#
# Features                                                 
# - Runs JS files through jslint to detect dangling commas 
#
# Requires jslint CLI installed.

if git rev-parse --verify HEAD >/dev/null 2>&1
then
        against=HEAD
else
        # Initial commit: diff against an empty tree object
        against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

exec 1>&2

for file in `git diff-index --name-status $against -- | cut -c3-` 
do
    if [ ${file: -3} == ".js" ]
    then
        linttest=`cat $file | jslint | grep 'Extra comma'`

        if [ "$linttest" ]
        then
            echo -e "COMMIT REJECTED: $file\n$linttest"
            exit 1;
        fi
    fi
done

exit;
